version: '3.8'

services:

  app:
    container_name: react-base-v3_container
    build: /workspace/react-base-v3
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start